// Builds an .ass subtitle file matching the CSS preview so what you see in
// the editor is what ffmpeg/libass burns into the export.

import type { CaptionPage, CaptionStyle } from "../types";

/** "#RRGGBB" -> ASS "&HAABBGGRR" (AA = alpha, 00 = opaque). */
function assColor(hex: string, alpha = 0): string {
  const h = hex.replace("#", "");
  const r = h.slice(0, 2);
  const g = h.slice(2, 4);
  const b = h.slice(4, 6);
  const a = alpha.toString(16).padStart(2, "0").toUpperCase();
  return `&H${a}${b}${g}${r}`.toUpperCase();
}

function assTime(t: number): string {
  const cs = Math.max(0, Math.round(t * 100));
  const h = Math.floor(cs / 360000);
  const m = Math.floor((cs % 360000) / 6000);
  const s = Math.floor((cs % 6000) / 100);
  const c = cs % 100;
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(c).padStart(2, "0")}`;
}

function esc(text: string): string {
  return text.replace(/\{/g, "(").replace(/\}/g, ")").replace(/\n/g, " ");
}

export interface AssOptions {
  playResX: number;
  playResY: number;
}

export function buildAss(pages: CaptionPage[], style: CaptionStyle, opts: AssOptions): string {
  const fontSize = Math.round((style.fontSizePct / 100) * opts.playResY);
  const outlineW = Math.max(0, (style.outlineWidthPct / 100) * opts.playResY);
  const marginV = Math.round(opts.playResY * (1 - style.positionPct / 100));
  const primary = assColor(style.fill);
  const outline = assColor(style.outline);
  const boxMode = style.boxColor != null;
  // BorderStyle 3 = opaque box; box color lives in OutlineColour, its alpha in that colour's AA.
  const boxAlphaHex = boxMode ? style.boxColor!.replace("#", "").slice(6, 8) || "00" : "00";
  const boxAlpha = boxMode ? 255 - parseInt(boxAlphaHex, 16) : 0; // ASS alpha is inverted
  const backColour = boxMode
    ? assColor("#" + style.boxColor!.replace("#", "").slice(0, 6), boxAlpha)
    : "&H80000000";

  const header = `[Script Info]
; Generated by ClipCaption
ScriptType: v4.00+
PlayResX: ${opts.playResX}
PlayResY: ${opts.playResY}
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Cap,${style.font},${fontSize},${primary},${primary},${boxMode ? backColour : outline},${backColour},-1,0,0,0,100,100,0,0,${boxMode ? 3 : 1},${boxMode ? Math.max(outlineW, fontSize * 0.12).toFixed(1) : outlineW.toFixed(1)},${style.shadow && !boxMode ? (outlineW * 1.5).toFixed(1) : "0"},2,40,40,${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const lines: string[] = [];
  const activeC = assColor(style.activeFill);

  for (const page of pages) {
    const words = page.words;
    if (!words.length) continue;

    // A diarized page uses its speaker's color instead of the style's
    // default fill, so alternating speakers read as visually distinct.
    const pagePrimary =
      page.speaker != null
        ? assColor(style.speakerColors[page.speaker % style.speakerColors.length])
        : primary;

    if (style.animation === "none") {
      const text = words.map((w) => wordText(w.text, style)).join(" ");
      lines.push(dialogue(page.start, page.end, `{\\fad(40,40)}{\\1c${pagePrimary}}${esc(text)}`));
      continue;
    }

    // One dialogue line per active-word window; the active word gets
    // highlight color + a pop/bounce scale transform.
    for (let i = 0; i < words.length; i++) {
      const start = words[i].start;
      const end = i + 1 < words.length ? Math.max(words[i + 1].start, words[i].end) : page.end;
      if (end - start < 0.01) continue;

      const parts: string[] = [];
      for (let j = 0; j < words.length; j++) {
        const t = esc(wordText(words[j].text, style));
        if (j === i) {
          let anim = "";
          if (style.animation === "pop") {
            anim = `\\t(0,90,\\fscx116\\fscy116)\\t(90,170,\\fscx100\\fscy100)`;
          } else if (style.animation === "bounce") {
            anim = `\\t(0,110,\\fscx122\\fscy122)\\t(110,240,\\fscx100\\fscy100)`;
          }
          parts.push(`{\\1c${activeC}${anim}}${t}{\\1c${pagePrimary}\\fscx100\\fscy100}`);
        } else {
          parts.push(`{\\1c${pagePrimary}}${t}`);
        }
      }
      const fade = i === 0 ? "{\\fad(40,0)}" : "";
      lines.push(dialogue(start, end, fade + parts.join(" ")));
    }
  }

  return header + lines.join("\n") + "\n";

  function dialogue(start: number, end: number, text: string): string {
    return `Dialogue: 0,${assTime(start)},${assTime(end)},Cap,,0,0,0,,${text}`;
  }
}

function wordText(text: string, style: CaptionStyle): string {
  const t = text.trim();
  return style.uppercase ? t.toUpperCase() : t;
}
