// Builds an .ass subtitle file matching the CSS preview so what you see in
// the editor is what ffmpeg/libass burns into the export.

import type { CaptionPage, CaptionStyle } from "../types";
import { lighten } from "./styles";
import { captionDynamics } from "./captions";

/** "#RRGGBB" -> ASS "&HAABBGGRR" (AA = alpha, 00 = opaque). */
function assColor(hex: string, alpha = 0): string {
  const h = hex.replace("#", "");
  const r = h.slice(0, 2);
  const g = h.slice(2, 4);
  const b = h.slice(4, 6);
  const a = alpha.toString(16).padStart(2, "0").toUpperCase();
  return `&H${a}${b}${g}${r}`.toUpperCase();
}

function assTime(t: number): string {
  const cs = Math.max(0, Math.round(t * 100));
  const h = Math.floor(cs / 360000);
  const m = Math.floor((cs % 360000) / 6000);
  const s = Math.floor((cs % 6000) / 100);
  const c = cs % 100;
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(c).padStart(2, "0")}`;
}

function esc(text: string): string {
  return text.replace(/\{/g, "(").replace(/\}/g, ")").replace(/\n/g, " ");
}

export interface AssOptions {
  playResX: number;
  playResY: number;
}

export function buildAss(pages: CaptionPage[], style: CaptionStyle, opts: AssOptions): string {
  const fontSize = Math.round((style.fontSizePct / 100) * opts.playResY);
  const outlineW = Math.max(0, (style.outlineWidthPct / 100) * opts.playResY);
  const marginV = Math.round(opts.playResY * (1 - style.positionPct / 100));
  const primary = assColor(style.fill);
  const outline = assColor(style.outline);
  const boxMode = style.boxColor != null;
  // BorderStyle 3 = opaque box; box color lives in OutlineColour, its alpha in that colour's AA.
  const boxAlphaHex = boxMode ? style.boxColor!.replace("#", "").slice(6, 8) || "00" : "00";
  const boxAlpha = boxMode ? 255 - parseInt(boxAlphaHex, 16) : 0; // ASS alpha is inverted
  const backColour = boxMode
    ? assColor("#" + style.boxColor!.replace("#", "").slice(0, 6), boxAlpha)
    : "&H80000000";
  // ASS's Bold field is a plain on/off flag, not a numeric weight — libass
  // will synthetically embolden a non-bold font when it's set, which looks
  // mushy on a preset that deliberately picked a lighter weight (e.g. Retro's
  // Impact, already heavy by design). Only flip it on for presets actually
  // asking for a bold/black look.
  const boldFlag = (style.fontWeight ?? 900) >= 700 ? -1 : 0;

  const header = `[Script Info]
; Generated by ClipCaption
ScriptType: v4.00+
PlayResX: ${opts.playResX}
PlayResY: ${opts.playResY}
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Cap,${style.font},${fontSize},${primary},${primary},${boxMode ? backColour : outline},${backColour},${boldFlag},0,0,0,100,100,0,0,${boxMode ? 3 : 1},${boxMode ? Math.max(outlineW, fontSize * 0.12).toFixed(1) : outlineW.toFixed(1)},${style.shadow && !boxMode ? (outlineW * 1.5).toFixed(1) : "0"},2,40,40,${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const lines: string[] = [];
  const activeC = assColor(style.activeFill);

  for (const page of pages) {
    const words = page.words;
    if (!words.length) continue;

    // The same numbers the live preview uses (see captionDynamics), expressed
    // as ASS overrides so the burn-in matches the editor.
    const dyn = captionDynamics(page, style);
    const prefix: string[] = [];
    if (style.dynamic) {
      // an5 + pos anchors the line at its own centre, which is exactly how the
      // CSS preview positions it (top: positionPct%, translateY -50%) - unlike
      // the style's default bottom-anchored MarginV, which would drift against
      // the preview as the caption's size changes.
      const x = Math.round(opts.playResX * (0.5 + dyn.offsetPct / 100));
      const y = Math.round(opts.playResY * (style.positionPct / 100));
      prefix.push(`\\an5\\pos(${x},${y})`);
      if (dyn.scale !== 1) {
        // fs (font size) rather than fscx/fscy: the per-word pop/bounce
        // animations below own those, and their reset to 100 afterwards would
        // wipe out a page-level scale set the same way.
        prefix.push(`\\fs${Math.round(fontSize * dyn.scale)}`);
      }
      // Skipped when the preset's own animation is "shake" - that already
      // drives frz per word, and two rotations fighting over one line reads as
      // a glitch rather than a shout.
      if (dyn.shake && style.animation !== "shake") {
        prefix.push("\\t(0,60,\\frz-4)\\t(60,120,\\frz4)\\t(120,180,\\frz-3)\\t(180,240,\\frz3)\\t(240,300,\\frz0)");
      }
    }
    const pre = prefix.length ? `{${prefix.join("")}}` : "";

    // A diarized page uses its speaker's color instead of the style's
    // default fill, so alternating speakers read as visually distinct.
    const pagePrimaryHex =
      page.speaker != null ? style.speakerColors[page.speaker % style.speakerColors.length] : style.fill;
    const pagePrimary = assColor(pagePrimaryHex);

    if (style.animation === "none") {
      const text = words.map((w) => wordText(w.text, style)).join(" ");
      lines.push(dialogue(page.start, page.end, `${pre}{\\fad(40,40)}{\\1c${pagePrimary}}${esc(text)}`));
      continue;
    }

    // One dialogue line per active-word window; the active word gets
    // highlight color + a pop/bounce scale transform.
    for (let i = 0; i < words.length; i++) {
      const start = words[i].start;
      const end = i + 1 < words.length ? Math.max(words[i + 1].start, words[i].end) : page.end;
      if (end - start < 0.01) continue;

      // Same reasoning as the CSS preview (styles.ts wordCss): the active
      // word is the most prominent thing on screen, so if it always used one
      // global activeC regardless of speaker, a diarized export would look
      // like it wasn't colored by speaker at all the instant a word became
      // active. Lighten that speaker's own color instead when one is known.
      const wordActiveC = page.speaker != null ? assColor(lighten(pagePrimaryHex, 0.55)) : activeC;

      const parts: string[] = [];
      for (let j = 0; j < words.length; j++) {
        const t = esc(wordText(words[j].text, style));
        if (j === i) {
          let anim = "";
          if (style.animation === "pop") {
            anim = `\\t(0,90,\\fscx116\\fscy116)\\t(90,170,\\fscx100\\fscy100)`;
          } else if (style.animation === "bounce") {
            anim = `\\t(0,110,\\fscx122\\fscy122)\\t(110,240,\\fscx100\\fscy100)`;
          } else if (style.animation === "karaoke") {
            anim = `\\t(0,65,\\fscx108\\fscy108)\\t(65,130,\\fscx100\\fscy100)`;
          } else if (style.animation === "glow") {
            anim = `\\t(0,80,\\blur6\\fscx106\\fscy106)\\t(80,260,\\blur0\\fscx100\\fscy100)`;
          } else if (style.animation === "shake") {
            anim = `\\t(0,45,\\frz-4)\\t(45,90,\\frz4)\\t(90,135,\\frz-3)\\t(135,180,\\frz3)\\t(180,220,\\frz0)`;
          }
          parts.push(`{\\1c${wordActiveC}${anim}}${t}{\\1c${pagePrimary}\\fscx100\\fscy100\\blur0\\frz0}`);
        } else {
          parts.push(`{\\1c${pagePrimary}}${t}`);
        }
      }
      const fade = i === 0 ? "{\\fad(40,0)}" : "";
      lines.push(dialogue(start, end, pre + fade + parts.join(" ")));
    }
  }

  return header + lines.join("\n") + "\n";

  function dialogue(start: number, end: number, text: string): string {
    return `Dialogue: 0,${assTime(start)},${assTime(end)},Cap,,0,0,0,,${text}`;
  }
}

function wordText(text: string, style: CaptionStyle): string {
  const t = text.trim();
  return style.uppercase ? t.toUpperCase() : t;
}
